export { default as Main } from './navbar/Main'
export { default as Signup } from './signup/Sigup'
export { default as Signin } from './signin/Signin'
export { default as  Draft}  from './showcase/Draft'
export { default as  Login}  from './login/Login'
export { default as  Setup}  from './setup/Setup'
export { default as  Notepage}  from './note/Notepage'
export { default as  Delete}  from './delete/Delete'